<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Migrations\Migrator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schema;

/**
 * Writes a MySQL script that creates every table, records the migrations as
 * run and inserts the admin account, for importing through phpMyAdmin on a
 * host without SSH. Needs no database connection: Laravel only "pretends"
 * to run the migrations and records the SQL.
 *
 * A later `php artisan migrate` (e.g. after moving to Hostinger) sees the
 * recorded migrations and only runs newer ones.
 */
class ExportSchemaSql extends Command
{
    protected $signature = 'deploy:schema-sql
        {path : File to write, e.g. ../deploy-build/infinityfree/database.sql}
        {--without-admin : Leave out the admin account}';

    protected $description = 'Write a phpMyAdmin-ready SQL file with all tables and the admin account';

    public function handle(Migrator $migrator): int
    {
        DB::setDefaultConnection('mysql');
        Schema::clearResolvedInstance('db.schema');
        $connection = DB::connection('mysql');

        $files = $migrator->getMigrationFiles(database_path('migrations'));

        $queries = $connection->pretend(function () use ($files) {
            app('migration.repository')->setSource('mysql');
            app('migration.repository')->createRepository();

            foreach ($files as $path) {
                (require $path)->up();
            }
        });

        $sql = [
            '-- Generated by `php artisan deploy:schema-sql` on '.now()->toDateTimeString().' UTC.',
            '-- Import into an EMPTY database (phpMyAdmin: select the database, Import tab).',
            'SET NAMES utf8mb4;',
            'SET foreign_key_checks = 0;',
            '',
            ...array_map(fn (array $query) => $query['query'].';', $queries),
            '',
            'INSERT INTO `migrations` (`migration`, `batch`) VALUES',
            implode(",\n", array_map(fn (string $name) => '  ('.self::literal($name).', 1)', array_keys($files))).';',
        ];

        if (! $this->option('without-admin')) {
            ['name' => $name, 'email' => $email, 'password' => $password] = config('leads.admin');

            if (! filter_var($email, FILTER_VALIDATE_EMAIL) || strlen((string) $password) < 12) {
                $this->error('Set ADMIN_EMAIL and ADMIN_PASSWORD (12+ characters), or pass --without-admin.');

                return self::FAILURE;
            }

            $now = self::literal(now()->toDateTimeString());
            $sql[] = '';
            $sql[] = 'INSERT INTO `users` (`name`, `email`, `password`, `created_at`, `updated_at`) VALUES ('
                .implode(', ', [self::literal($name ?: 'Admin'), self::literal(strtolower($email)), self::literal(Hash::make($password)), $now, $now]).');';
        }

        $sql[] = '';
        $sql[] = 'SET foreign_key_checks = 1;';

        File::ensureDirectoryExists(dirname($this->argument('path')));
        File::put($this->argument('path'), implode("\n", $sql)."\n");

        $this->components->info('Wrote '.$this->argument('path'));

        return self::SUCCESS;
    }

    /**
     * A MySQL string literal. Plain text when it cannot contain quotes or
     * backslashes; otherwise a hex value with a charset introducer, which is
     * safe for any character whatever the server's escaping mode.
     */
    private static function literal(string $value): string
    {
        return preg_match('/^[A-Za-z0-9_ .:@-]*$/', $value)
            ? "'{$value}'"
            : "_utf8mb4 X'".bin2hex($value)."'";
    }
}
